### PR TITLE
goesr

### PR DESCRIPTION
**Pull request by julienchastang**
would this be useful to you at all?

### CODE REVIEW

**Comment by dopplershift** [comment]
Eventually maybe, but only once we need this to get the full GOES-R feed on the main data machine. Right now these data aren't arriving on lead via LDM I believe.

**Comment by julienchastang** [comment]
Just for additional documentation purposes, this is basically an implementation of what Tom did here: [GOES-R ReBroadcast (GRB) Satellite Imagery ](https://www.unidata.ucar.edu/data/goesr.html).

**Comment by haileyajohnson** [comment]
This PR is 4 years old, can I close it?

**Comment by dopplershift** [comment]
I think we're already doing everything that this PR adds, so I think we can safely close.

**Pull request closed without merging**
