### PR TITLE
fixing missing DATA_DIR path

### PR DESCRIPTION
**Pull request by julienchastang**
fixing path issue in `pqact.radars`

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Good catch!

**Comment by dopplershift** [comment]
How was this even working?

**Comment by julienchastang** [comment]
Basically by accident, I believe. If your paths (CWD, etc. and soft links, perhaps) are coincidentally correct, it will work. But if you break assumptions, your data will end up in weird paths which was the problem I ran into.

**Comment by lesserwhirls** [comment]
Our systems have a symlink (data/) in the LDM_HOME directory of the LDM to
/data.

**Comment by julienchastang** [comment]
Coupled with the fact that the `registry.xml` probably looks like this:

```
  <pqact>
    <config-path>/home/ldm/etc/pqact.conf</config-path>
    <datadir-path>/home/ldm</datadir-path>
  </pqact>

```

mine was 

```
  <pqact>
    <config-path>/home/ldm/etc/pqact.conf</config-path>
    <datadir-path>/home/ldm/var/data</datadir-path>
  </pqact>

```

so the data were ending up in weird paths.

**Pull request merged**
