### PR TITLE
General Cleanup

### PR DESCRIPTION
**Pull request by lesserwhirls**
First pass a cleaning up the catalogs to remove datasets that are no longer produced. As part of that, this PR fixes Unidata/TdsConfig#94

### CODE REVIEW

**Review by dopplershift — APPROVED** [review]
I can't vouch that the syntax is perfect, but all the removals and edits seem in-line with what I remember has been removed.

**Comment by dopplershift** [comment]
@lesserwhirls You said "first pass"...should I merge?

**Comment by lesserwhirls** [comment]
I think so. Lots more to do focusing on MRMS, but that's a mix of cleanup and new. Also need to do a pass to compare current catalogs with what actually exists on those machines, because my guess is they are out of sync and I'd hate to lose anyone stuff.

**Comment by dopplershift** [comment]
Sounds good.

**Pull request merged**
