### PR TITLE
ENH: Add restricted dataset to thredds-dev

### PR DESCRIPTION
**Pull request by lesserwhirls**
Add a restricted dataset for client testing purposes

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
I thought we already had one. How is this different?

**Comment by lesserwhirls** [comment]
As far as I know, we didn't have one. Do you know where is it located?

**Comment by DennisHeimbigner** [comment]
I was thinking of the restricted dataset test in
thredds/tds/src/test/content/thredds/catalog.xml

**Comment by lesserwhirls** [comment]
Ah, yes. Those are good for our integration tests, but we currently do not have a test dataset for other clients, such as Siphon or the IDV, to easily test and develop against. This puts up a test dataset on http://thredds-dev.unidata.ucar.edu/thredds/catalog.html

That said, the catalog you point to has both `dataset` and `datasetScan` elements using restriction, but I could only get `datasetScan` elements to be restricted (still looking to see if I am doing something wrong). Do you know if we have integration tests hitting all of those restricted datasets in the test `catalog.xml`?

**Comment by lesserwhirls** [comment]
Actually, `thredds-dev` and the default set of catalogs and datasets shipped with the TDS are quite different. thredds-dev.unidata.ucar.edu is pretty much the same as thredds.ucar.edu, but it's running 5.0. The breakdown is like this, in theory:

Server | Role
------------ | -------------
http://thredds.ucar.edu/thredds/catalog.html | production  "Production" server
http://thredds-test.unidata.ucar.edu/thredds/catalog.html | Release candidate server for community to test against
http://thredds-dev.unidata.ucar.edu/thredds/catalog.html | Server for us to put up snapshots to test against live data

At this point, I am of the opinion that roles of `thredds-test` and `thredds-dev` can be assumed by `thredds-test` alone, and that `thredds-dev` should really be a "test" server for the community that exercises the full functionality of the TDS, not just the limited things that are exercised by the data we get from NCEP (this idea is on our agenda for our meeting today). This would also allow clients other than netCDF-java to exercise and develop capabilities against the wide variety of things the TDS can do, including restricted access datasets.

**Pull request merged**
