### PR TITLE
Increase NCSS response limit from 50 MB to 600 MB

### PR DESCRIPTION
**Pull request by lesserwhirls**

### CODE REVIEW

**Comment by lesserwhirls** [comment]
I'll bump the configs on motherlode once this is merged.

**Comment by dopplershift** [comment]
Helpful, but this request:

http://thredds.ucar.edu/thredds/ncss/grib/NCEP/NAM/CONUS_12km/NAM_CONUS_12km_20170607_1200.grib2?var=v-component_of_wind_isobaric&var=Temperature_isobaric&var=u-component_of_wind_isobaric&var=Relative_humidity_isobaric&time_start=2017-06-07T12%3A00%3A00&time_end=2017-06-11T02%3A00%3A00&west=-150&east=-50&south=15&north=60&addLatLon=True&accept=netcdf4

Wants to return 600MB. So...?

**Comment by lesserwhirls** [comment]
I bumped it up to 600 MB, but that does not "feel" like much of a subset (although at a grid spacing of 12km, it's not hard to get that big).

So essentially you are grabbing the four full fields with no temporal (the requests ask for two more hours than are in the run) or spatial subsetting (well, very little spatial subsetting)? Why not just use opendap to grab the fields?

**Comment by dopplershift** [comment]
This came from one of our summer students, so I can't speak to why NCSS vs. OPeNDAP. 

I would say in general OPeNDAP vs. NCSS is a perennial user education problem we have.

**Comment by lesserwhirls** [comment]
600 MB feels too big to me, but I understand that's pretty subjective. I don't know how performance will be, but it's worth a test. We used to run NCSS with unlimited request size, and we had performance issues. Not sure where those started to creep in though.

**Pull request merged**
