### PR TITLE
Update RadarL2Stations.xml

### PR DESCRIPTION
**Pull request by lesserwhirls**
We do not receive data from KCRI or NOP3 - not sure when the last time we did - so removing from the level 2 stations list.

### CODE REVIEW

**Comment by dopplershift** [comment]
Why do we need to remove?

**Comment by dopplershift** [comment]
(oops)

**Comment by lesserwhirls** [comment]
This PR is a result of the conversations we had with the IDV group. They use the stations list advertised by a TDS radar server to drive their site selection GUI. One could argue that their particular issue is a presentation layer issue and should be dealt with accordingly. However, if data for a site are not coming currently coming across the IDD to even be potentially served by a TDS radar server, then I think it make sense to remove them from being advertised in the station list used by the `idd` configs. Note that I didn't remove them from the `awsL2` station list, as those sites might have data in the AWS archive, and we still have the sites in the netCDF-Java codebase for use in the IOSP.

**Comment by dopplershift** [comment]
Fair enough. I just wondered because I *have* seen data for NOP4 lately. All of KCRI, NOP3, and NOP4 are test systems in Norman.

**Comment by lesserwhirls** [comment]
If there is a chance we will get data from them and they are not decommissioned, then perhaps we should keep them?

**Comment by dopplershift** [comment]
So the question is: do we want the non-operational radars included in the site table? I can see it being useful myself. Here's the latest document I can find on the sites:

https://www.roc.noaa.gov/wsr88d/PublicDocs/Level_II/ListOf_Level2_Sites.pdf

See the bottom for the mention of the IDs in question.

**Comment by lesserwhirls** [comment]
If so, we could probably do better than two decimals lat/lon, at least on these sites. Do you happen to know of a resource with this info?

**Comment by lesserwhirls** [comment]
Between the information in these two AWIPS2 files:

https://github.com/Unidata/awips2/blob/unidata_18.1.1/rpms/awips2.core/Installer.localization/coords_wsr88d.dat
https://github.com/Unidata/awips2/blob/unidata_18.1.1/rpms/awips2.core/Installer.localization/radar_maps.sh

we could potentially have better location information. 

The document from the ROC says:

> Sporadic Level 2 data in real time and at NCDC from (DAN1, DOP1, FOP1, NOP3, NOP4, and ROP4) are from the Radar Operations Center test beds WSR-88D systems (KOUN and KCRI)

So does that mean, at least in terms of physical location, `DAN1`, `DOP1`, `FOP1`, `NOP3`, `NOP4`, and `ROP4` are aliases for `KOUN` and `KCRI`? Also, with the exception of `KCRI`, the AWIPS location information does not include any of these.

**Comment by dopplershift** [comment]
I think they are aliases, no idea what affects which one is used, or how to tell what corresponds to KCRI vs. KOUN. Those two are within a few hundred feet of each other, so it may be that they just don't bother adjusting. Also, level2 data itself has lat/lons, so people doing applications where a few hundred feet matters (I'm thinking clutter targets), probably are using lat/lons from in the file rather than a table.

Long way to say: we can probably just use the location for KCRI for all of those in our xml file.

**Comment by dopplershift** [comment]
@lesserwhirls Did you mean to push this commit here?

**Comment by lesserwhirls** [comment]
I removed `.travis.yml` from all three branches on this repo, just for good measure. 💥

**Comment by lesserwhirls** [comment]
Although, the two other than `master` could probably be removed.

**Comment by dopplershift** [comment]
NOP3 was commented out in 0af4045836bcf09cfc10815a0e8f3c8bd8d9d081, so I think we can close this now. (I knew that sounded familiar @haileyajohnson).

**Pull request closed without merging**
