### PR TITLE
Update for TDS 5 migration

### PR DESCRIPTION
**Pull request by dopplershift**
* Split up and remote thredds-test
  - Some of this was TDS 5 updates that needed to be synced to the main config
  - Also moved text products and some updated satellite data (NOAA-20, blended products) to listing
  - Moved a lot of dev/testing stuff to threddsDev
* Removed defunct observation data using netcdf-perl decoders that we can't get to build. Long live `metar2nc.new.1.2`!
* Removed a lot of other catalogs/pqact entries for data we no longer get, mostly legacy satellite stuff
* Removed any thredds catalogs/configs that were no longer actually overriding things

### CODE REVIEW

**Comment by tdrwenski** [comment]
I think `idd/obsData.xml` can also be deleted-- I don't see that being used anywhere since you removed the reference to it from the two `catalog.xml`s

**Comment by tdrwenski** [comment]
Found one more reference to `thredds-test.unidata.ucar.edu` in `threddsDev/notebooks/README.md` that I think should be `thredds-dev`

**Comment by dopplershift** [comment]
Good catches. Fixed.

**Comment by tdrwenski** [comment]
I also still see four references to `tds-test` that may need updating?
```
grep -Ir tds-test
./threddsDev/cf_examples.xml:  <datasetScan name="CF 1.6 Discrete Sampling Geometry (DSG) point file examples" path="pointData/cf_dsg/example" location="/data/thredds/tds-test/content/thredds/public/cfDsgExamples">
./threddsDev/cf_examples.xml:  <datasetScan name="CF 1.6 Discrete Sampling Geometry (DSG) appendix H examples" path="pointData/cf_doc_dsg/example" location="/data/thredds/tds-test/content/thredds/public/cfDocDsgExamples">
./threddsDev/tdsconfig_tools/config_update.sh:TDS_PQACT_DIR="/opt/tds-test/content/thredds/pqacts"
./threddsDev/tdsconfig_tools/pqact_diff.sh:TDS_PQACT_DIR="/opt/tds-test/content/thredds/pqacts"
```

**Comment by dopplershift** [comment]
Another good catch. Fixed.

**Review by tdrwenski — APPROVED** [review]

**Pull request merged**
